Fix check_data.c to compile under musl-libc
Running `make full-check` on musl systems fails because:
```
tests/check_data.c:6:10: fatal error: error.h: No such file or directory
 #include <error.h>
          ^~~~~~~~~
compilation terminated.
```
as `check_data.c` does not use any of the functions defined in the library, it's safe to make this change.